@isTest
public class TestForcating{
    static testMethod void insertNewUser(){
        User userToCreate = new User();
        
        userToCreate.FirstName='Mahindra';
        userToCreate.LastName='Dhoni';
        //userToCreate.Company='BCCI';
        
       userToCreate.Email     = 'dvdkliu+sfdc99@gmail.com';
       userToCreate.Username  = 'sfdc-dreamer@gmail.com';
       userToCreate.Alias     = 'fatty';
       userToCreate.ProfileId = '00ei0000000rTfp';
        
    }
}